#name: Deploy Master
#
#on:
#  push:
#    branches:
#    - main
#
#jobs:
#  build:
#    runs-on: ubuntu-latest
#    strategy:
#      matrix:
#        node-version: [14.x]
#
#    steps:
#    - uses: actions/checkout@v1
#
#    - name: Cache node modules
#      uses: actions/cache@v1
#      with:
#        path: ~/.npm
#        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
#        restore-keys: |
#          ${{ runner.os }}-node-
#
#    - name: Node ${{ matrix.node-version }}
#      uses: actions/setup-node@v1
#      with:
#        node-version: ${{ matrix.node-version }}
#
#    - name: Installing NPM
#      run: npm install
#
#    - name: Get Time
#      id: time
#      uses: nanzm/get-time-action@v1.1
#      with:
#        timeZone: 8
#        format: 'YYYY-MM-DD-HH-mm'
#    - name: Set up JDK 11
#      uses: actions/setup-java@v1
#      with:
#        java-version: 1.11
#    - name: Maven Package
#      run: mvn clean install -DskipTests -Paws
#
#    - name: rename target .jar file
#      run: mv target/gip5-starter-1.0.jar target/deploy-${{ steps.time.outputs.time }}.jar
#
#    - name: Set up beanstalk
#      uses: snakehead007/beanstalk-deploy@jar
#      with:
#        aws_access_key: ${{secrets.AWS_ACCESS_KEY_ID}}
#        aws_secret_key: ${{secrets.AWS_SECRET_ACCESS_KEY}}
#        application_name: ucll-team3-gip5-web
#        environment_name: Ucllteam3gip5web-env
#        region: eu-west-1
#        version_label: "stable-${{ steps.time.outputs.time }}"
#        version_description: ${{ github.event.head_commit.message }}
#        deployment_package: target/deploy-${{ steps.time.outputs.time }}.jar
#        wait_for_environment_recovery: 120
#
#    - name: Deployed!
#      run: echo App deployed to ELB
